apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cjhn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cjhn
    app.kubernetes.io/part-of: byoc-app-kdot
  name: cjhn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: cjhn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: cjhn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-pcna-tenant/byoc-app-kdot/cjhn@sha256:441619252a1ad647f119da4509800896ec6c4f6914008e36cd6651b0c6388152
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
