apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cjhn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cjhn
    app.kubernetes.io/part-of: byoc-app-kdot
  name: cjhn
spec:
  rules:
  - host: cjhn-byoc-pcna-tenant.apps.482bc542d2177ec4c363.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: cjhn
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
